//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrendsDataToDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class 搜尋趨勢表主檔
    {
        public int ID { get; set; }
        public string 關鍵字 { get; set; }
        public string 地區 { get; set; }
        public Nullable<System.DateTime> startTime { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
        public int 相對搜尋比 { get; set; }
        public Nullable<bool> 正負指向 { get; set; }
    }
}
